[project]
name = "steam-deck-repo-manager"
version = "0.1.0"
description = "A native GUI manager for Steam Deck boot and suspend videos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.10.1",
]
